// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProduct(arg1:number,arg2:string,arg3:string):Promise<number>;

export function AttachImageFromFile(arg1:number,arg2:string):Promise<string>;

export function AttachImageFromURL(arg1:number,arg2:string):Promise<string>;

export function CreateBagWithSet(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function CreateBox(arg1:number,arg2:string,arg3:string):Promise<number>;

export function CreateLocation(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function CreateManufacturer(arg1:string):Promise<number>;

export function CreateManufacturerIfMissing(arg1:string):Promise<number>;

export function CreateTag(arg1:string):Promise<number>;

export function CreateTagIfMissing(arg1:string):Promise<number>;

export function CreateType(arg1:string):Promise<number>;

export function CreateTypeIfMissing(arg1:string):Promise<number>;

export function DeleteBox(arg1:number):Promise<void>;

export function DeleteLocation(arg1:number):Promise<void>;

export function DeleteManufacturer(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeleteSet(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteType(arg1:number):Promise<void>;

export function GetAppPaths():Promise<main.AppPaths>;

export function GetNextBagSerial(arg1:number):Promise<string>;

export function GetSet(arg1:number):Promise<main.SetDetails>;

export function ListBoxes(arg1:number):Promise<Array<main.Box>>;

export function ListLocations():Promise<Array<main.StorageLocation>>;

export function ListManufacturers():Promise<Array<main.Manufacturer>>;

export function ListProductsBySet(arg1:number):Promise<Array<main.Product>>;

export function ListTags():Promise<Array<string>>;

export function ListTagsFull():Promise<Array<main.Tag>>;

export function ListTypes():Promise<Array<main.Type>>;

export function OpenAppFolder():Promise<void>;

export function ResolveImagePath(arg1:string):Promise<string>;

export function SaveCroppedImage(arg1:number,arg2:string,arg3:string):Promise<string>;

export function SearchSets(arg1:string,arg2:string):Promise<Array<main.SetSearchResult>>;

export function SetTags(arg1:number,arg2:Array<string>):Promise<void>;

export function UpdateBox(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function UpdateLocation(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateManufacturer(arg1:number,arg2:string):Promise<void>;

export function UpdateProduct(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateSet(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<void>;

export function UpdateTag(arg1:number,arg2:string):Promise<void>;

export function UpdateType(arg1:number,arg2:string):Promise<void>;
