// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProduct(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProduct'](arg1, arg2, arg3);
}

export function AttachImageFromFile(arg1, arg2) {
  return window['go']['main']['App']['AttachImageFromFile'](arg1, arg2);
}

export function AttachImageFromURL(arg1, arg2) {
  return window['go']['main']['App']['AttachImageFromURL'](arg1, arg2);
}

export function CreateBagWithSet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateBagWithSet'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateBox(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBox'](arg1, arg2, arg3);
}

export function CreateLocation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateLocation'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateManufacturer(arg1) {
  return window['go']['main']['App']['CreateManufacturer'](arg1);
}

export function CreateManufacturerIfMissing(arg1) {
  return window['go']['main']['App']['CreateManufacturerIfMissing'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function CreateTagIfMissing(arg1) {
  return window['go']['main']['App']['CreateTagIfMissing'](arg1);
}

export function CreateType(arg1) {
  return window['go']['main']['App']['CreateType'](arg1);
}

export function CreateTypeIfMissing(arg1) {
  return window['go']['main']['App']['CreateTypeIfMissing'](arg1);
}

export function DeleteBox(arg1) {
  return window['go']['main']['App']['DeleteBox'](arg1);
}

export function DeleteLocation(arg1) {
  return window['go']['main']['App']['DeleteLocation'](arg1);
}

export function DeleteManufacturer(arg1) {
  return window['go']['main']['App']['DeleteManufacturer'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteSet(arg1) {
  return window['go']['main']['App']['DeleteSet'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteType(arg1) {
  return window['go']['main']['App']['DeleteType'](arg1);
}

export function GetAppPaths() {
  return window['go']['main']['App']['GetAppPaths']();
}

export function GetNextBagSerial(arg1) {
  return window['go']['main']['App']['GetNextBagSerial'](arg1);
}

export function GetSet(arg1) {
  return window['go']['main']['App']['GetSet'](arg1);
}

export function ListBoxes(arg1) {
  return window['go']['main']['App']['ListBoxes'](arg1);
}

export function ListLocations() {
  return window['go']['main']['App']['ListLocations']();
}

export function ListManufacturers() {
  return window['go']['main']['App']['ListManufacturers']();
}

export function ListProductsBySet(arg1) {
  return window['go']['main']['App']['ListProductsBySet'](arg1);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function ListTagsFull() {
  return window['go']['main']['App']['ListTagsFull']();
}

export function ListTypes() {
  return window['go']['main']['App']['ListTypes']();
}

export function OpenAppFolder() {
  return window['go']['main']['App']['OpenAppFolder']();
}

export function ResolveImagePath(arg1) {
  return window['go']['main']['App']['ResolveImagePath'](arg1);
}

export function SaveCroppedImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCroppedImage'](arg1, arg2, arg3);
}

export function SearchSets(arg1, arg2) {
  return window['go']['main']['App']['SearchSets'](arg1, arg2);
}

export function SetTags(arg1, arg2) {
  return window['go']['main']['App']['SetTags'](arg1, arg2);
}

export function UpdateBox(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateBox'](arg1, arg2, arg3, arg4);
}

export function UpdateLocation(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateLocation'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateManufacturer(arg1, arg2) {
  return window['go']['main']['App']['UpdateManufacturer'](arg1, arg2);
}

export function UpdateProduct(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3);
}

export function UpdateSet(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateSet'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateTag(arg1, arg2) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2);
}

export function UpdateType(arg1, arg2) {
  return window['go']['main']['App']['UpdateType'](arg1, arg2);
}
